apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: my_target
  namespace: argocd
spec:
  destination:
    namespace: team-025
    server: https://k8s-api.staging.mydomain.com
  project: proj1
  source:
    helm:
      parameters:
        - name: env.LOG_LEVEL
          value: DEBUG
    path: chart
    repoURL: git@github.com:myorg/app1.git
    targetRevision: staging
